
# Create comprehensive APIs data file with 50+ real APIs
apis_data = '''[
  {
    "id": "1",
    "name": "OpenWeatherMap",
    "category": "Weather",
    "description": "Comprehensive weather data API providing current weather, forecasts, and historical data",
    "base_url": "https://api.openweathermap.org/data/2.5",
    "auth_type": "apikey",
    "docs_url": "https://openweathermap.org/api",
    "example_endpoint": "/weather?q=London&appid=YOUR_API_KEY",
    "tags": ["weather", "forecast", "climate", "geolocation"],
    "status": "unknown"
  },
  {
    "id": "2",
    "name": "NewsAPI",
    "category": "News",
    "description": "Headlines currently published on a range of news sources and blogs",
    "base_url": "https://newsapi.org/v2",
    "auth_type": "apikey",
    "docs_url": "https://newsapi.org/docs",
    "example_endpoint": "/top-headlines?country=us&apiKey=YOUR_API_KEY",
    "tags": ["news", "headlines", "articles", "media"],
    "status": "unknown"
  },
  {
    "id": "3",
    "name": "JSONPlaceholder",
    "category": "Developer Tools",
    "description": "Fake REST API for testing and prototyping",
    "base_url": "https://jsonplaceholder.typicode.com",
    "auth_type": "none",
    "docs_url": "https://jsonplaceholder.typicode.com/",
    "example_endpoint": "/posts/1",
    "tags": ["testing", "mock", "rest", "prototype"],
    "status": "unknown"
  },
  {
    "id": "4",
    "name": "CoinGecko",
    "category": "Finance",
    "description": "Cryptocurrency data API with price, market cap, volume, and exchange data",
    "base_url": "https://api.coingecko.com/api/v3",
    "auth_type": "none",
    "docs_url": "https://www.coingecko.com/en/api",
    "example_endpoint": "/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10",
    "tags": ["crypto", "bitcoin", "ethereum", "market-data"],
    "status": "unknown"
  },
  {
    "id": "5",
    "name": "PokéAPI",
    "category": "Entertainment",
    "description": "The RESTful Pokémon API with over 800 Pokémon data",
    "base_url": "https://pokeapi.co/api/v2",
    "auth_type": "none",
    "docs_url": "https://pokeapi.co/docs/v2",
    "example_endpoint": "/pokemon/ditto",
    "tags": ["pokemon", "games", "nintendo", "fun"],
    "status": "unknown"
  },
  {
    "id": "6",
    "name": "Dog CEO",
    "category": "Entertainment",
    "description": "Random dog images and breed information",
    "base_url": "https://dog.ceo/api",
    "auth_type": "none",
    "docs_url": "https://dog.ceo/dog-api/",
    "example_endpoint": "/breeds/image/random",
    "tags": ["dogs", "images", "random", "fun"],
    "status": "unknown"
  },
  {
    "id": "7",
    "name": "OpenAI",
    "category": "AI",
    "description": "Access to GPT models for text generation, embeddings, and more",
    "base_url": "https://api.openai.com/v1",
    "auth_type": "apikey",
    "docs_url": "https://platform.openai.com/docs",
    "example_endpoint": "/chat/completions",
    "tags": ["ai", "gpt", "llm", "nlp", "machine-learning"],
    "status": "unknown"
  },
  {
    "id": "8",
    "name": "GitHub",
    "category": "Developer Tools",
    "description": "Access to GitHub repositories, users, issues, and more",
    "base_url": "https://api.github.com",
    "auth_type": "oauth",
    "docs_url": "https://docs.github.com/en/rest",
    "example_endpoint": "/users/octocat",
    "tags": ["git", "repositories", "code", "version-control"],
    "status": "unknown"
  },
  {
    "id": "9",
    "name": "NASA APOD",
    "category": "Science",
    "description": "NASA Astronomy Picture of the Day API",
    "base_url": "https://api.nasa.gov/planetary",
    "auth_type": "apikey",
    "docs_url": "https://api.nasa.gov/",
    "example_endpoint": "/apod?api_key=DEMO_KEY",
    "tags": ["space", "astronomy", "images", "science"],
    "status": "unknown"
  },
  {
    "id": "10",
    "name": "REST Countries",
    "category": "Data",
    "description": "Get information about countries via a RESTful API",
    "base_url": "https://restcountries.com/v3.1",
    "auth_type": "none",
    "docs_url": "https://restcountries.com/",
    "example_endpoint": "/all",
    "tags": ["countries", "geography", "data", "flags"],
    "status": "unknown"
  },
  {
    "id": "11",
    "name": "Open Brewery DB",
    "category": "Food & Drink",
    "description": "Public information on breweries, cideries, meaderies, and bottleshops",
    "base_url": "https://api.openbrewerydb.org/v1",
    "auth_type": "none",
    "docs_url": "https://www.openbrewerydb.org/",
    "example_endpoint": "/breweries",
    "tags": ["breweries", "beer", "drinks", "locations"],
    "status": "unknown"
  },
  {
    "id": "12",
    "name": "The Cat API",
    "category": "Entertainment",
    "description": "Random cat images and breed information",
    "base_url": "https://api.thecatapi.com/v1",
    "auth_type": "apikey",
    "docs_url": "https://docs.thecatapi.com/",
    "example_endpoint": "/images/search",
    "tags": ["cats", "images", "random", "fun"],
    "status": "unknown"
  },
  {
    "id": "13",
    "name": "Random User Generator",
    "category": "Developer Tools",
    "description": "Generate random user data for testing",
    "base_url": "https://randomuser.me/api",
    "auth_type": "none",
    "docs_url": "https://randomuser.me/",
    "example_endpoint": "?results=5",
    "tags": ["mock-data", "testing", "users", "fake-data"],
    "status": "unknown"
  },
  {
    "id": "14",
    "name": "IPify",
    "category": "Developer Tools",
    "description": "Simple IP address API - get your public IP address",
    "base_url": "https://api.ipify.org",
    "auth_type": "none",
    "docs_url": "https://www.ipify.org/",
    "example_endpoint": "?format=json",
    "tags": ["ip", "network", "geolocation", "utility"],
    "status": "unknown"
  },
  {
    "id": "15",
    "name": "HTTPBin",
    "category": "Developer Tools",
    "description": "HTTP Request & Response Service for testing",
    "base_url": "https://httpbin.org",
    "auth_type": "none",
    "docs_url": "https://httpbin.org/",
    "example_endpoint": "/get",
    "tags": ["testing", "http", "debug", "utility"],
    "status": "unknown"
  },
  {
    "id": "16",
    "name": "Chuck Norris Jokes",
    "category": "Entertainment",
    "description": "Chuck Norris facts and jokes API",
    "base_url": "https://api.chucknorris.io/jokes",
    "auth_type": "none",
    "docs_url": "https://api.chucknorris.io/",
    "example_endpoint": "/random",
    "tags": ["jokes", "fun", "random", "entertainment"],
    "status": "unknown"
  },
  {
    "id": "17",
    "name": "Deck of Cards",
    "category": "Entertainment",
    "description": "Simulate a deck of cards API for card games",
    "base_url": "https://deckofcardsapi.com/api/deck",
    "auth_type": "none",
    "docs_url": "https://deckofcardsapi.com/",
    "example_endpoint": "/new/shuffle/?deck_count=1",
    "tags": ["cards", "games", "random", "entertainment"],
    "status": "unknown"
  },
  {
    "id": "18",
    "name": "Open Library",
    "category": "Books",
    "description": "Books, covers, and library metadata from Open Library",
    "base_url": "https://openlibrary.org/api",
    "auth_type": "none",
    "docs_url": "https://openlibrary.org/developers/api",
    "example_endpoint": "/books?bibkeys=ISBN:0451526538&format=json",
    "tags": ["books", "library", "reading", "metadata"],
    "status": "unknown"
  },
  {
    "id": "19",
    "name": "Unsplash",
    "category": "Images",
    "description": "Beautiful free photos and images API",
    "base_url": "https://api.unsplash.com",
    "auth_type": "apikey",
    "docs_url": "https://unsplash.com/documentation",
    "example_endpoint": "/photos/random?client_id=YOUR_ACCESS_KEY",
    "tags": ["photos", "images", "stock", "design"],
    "status": "unknown"
  },
  {
    "id": "20",
    "name": "Reqres",
    "category": "Developer Tools",
    "description": "A hosted REST-API ready to respond to your AJAX requests",
    "base_url": "https://reqres.in/api",
    "auth_type": "none",
    "docs_url": "https://reqres.in/",
    "example_endpoint": "/users?page=2",
    "tags": ["testing", "mock", "rest", "prototype"],
    "status": "unknown"
  },
  {
    "id": "21",
    "name": "Exchange Rate API",
    "category": "Finance",
    "description": "Free currency conversion and exchange rates",
    "base_url": "https://api.exchangerate-api.com/v4/latest",
    "auth_type": "none",
    "docs_url": "https://www.exchangerate-api.com/",
    "example_endpoint": "/USD",
    "tags": ["currency", "exchange", "finance", "rates"],
    "status": "unknown"
  },
  {
    "id": "22",
    "name": "The Cocktail DB",
    "category": "Food & Drink",
    "description": "Cocktail recipes and ingredients database",
    "base_url": "https://www.thecocktaildb.com/api/json/v1/1",
    "auth_type": "none",
    "docs_url": "https://www.thecocktaildb.com/api.php",
    "example_endpoint": "/search.php?s=margarita",
    "tags": ["cocktails", "recipes", "drinks", "food"],
    "status": "unknown"
  },
  {
    "id": "23",
    "name": "Agify.io",
    "category": "Data",
    "description": "Predict age based on a name using data science",
    "base_url": "https://api.agify.io",
    "auth_type": "none",
    "docs_url": "https://agify.io/",
    "example_endpoint": "?name=michael",
    "tags": ["demographics", "prediction", "data", "fun"],
    "status": "unknown"
  },
  {
    "id": "24",
    "name": "Genderize.io",
    "category": "Data",
    "description": "Predict gender based on a name",
    "base_url": "https://api.genderize.io",
    "auth_type": "none",
    "docs_url": "https://genderize.io/",
    "example_endpoint": "?name=peter",
    "tags": ["demographics", "prediction", "data", "gender"],
    "status": "unknown"
  },
  {
    "id": "25",
    "name": "Nationalize.io",
    "category": "Data",
    "description": "Predict nationality based on a name",
    "base_url": "https://api.nationalize.io",
    "auth_type": "none",
    "docs_url": "https://nationalize.io/",
    "example_endpoint": "?name=nathaniel",
    "tags": ["demographics", "prediction", "nationality", "data"],
    "status": "unknown"
  },
  {
    "id": "26",
    "name": "Bored API",
    "category": "Entertainment",
    "description": "Find something to do when you're bored",
    "base_url": "https://www.boredapi.com/api",
    "auth_type": "none",
    "docs_url": "https://www.boredapi.com/",
    "example_endpoint": "/activity",
    "tags": ["activities", "fun", "random", "entertainment"],
    "status": "unknown"
  },
  {
    "id": "27",
    "name": "Quote Garden",
    "category": "Entertainment",
    "description": "A REST API for quotes with 7500+ quotes",
    "base_url": "https://quote-garden.onrender.com/api/v3",
    "auth_type": "none",
    "docs_url": "https://github.com/pprathameshmore/QuoteGarden",
    "example_endpoint": "/quotes/random",
    "tags": ["quotes", "inspiration", "random", "text"],
    "status": "unknown"
  },
  {
    "id": "28",
    "name": "Kanye.rest",
    "category": "Entertainment",
    "description": "Kanye West quotes API",
    "base_url": "https://api.kanye.rest",
    "auth_type": "none",
    "docs_url": "https://kanye.rest/",
    "example_endpoint": "/",
    "tags": ["quotes", "kanye", "fun", "random"],
    "status": "unknown"
  },
  {
    "id": "29",
    "name": "Rick and Morty",
    "category": "Entertainment",
    "description": "Rick and Morty character, location, and episode data",
    "base_url": "https://rickandmortyapi.com/api",
    "auth_type": "none",
    "docs_url": "https://rickandmortyapi.com/documentation",
    "example_endpoint": "/character",
    "tags": ["tv", "cartoon", "characters", "fun"],
    "status": "unknown"
  },
  {
    "id": "30",
    "name": "SpaceX API",
    "category": "Science",
    "description": "Open source SpaceX data about rockets, launches, and more",
    "base_url": "https://api.spacexdata.com/v4",
    "auth_type": "none",
    "docs_url": "https://github.com/r-spacex/SpaceX-API",
    "example_endpoint": "/launches/latest",
    "tags": ["space", "rockets", "spacex", "science"],
    "status": "unknown"
  },
  {
    "id": "31",
    "name": "JSONBin",
    "category": "Developer Tools",
    "description": "Free JSON storage and API testing",
    "base_url": "https://api.jsonbin.io/v3",
    "auth_type": "apikey",
    "docs_url": "https://jsonbin.io/",
    "example_endpoint": "/b/YOUR_BIN_ID",
    "tags": ["storage", "json", "database", "testing"],
    "status": "unknown"
  },
  {
    "id": "32",
    "name": "QRCode Monkey",
    "category": "Developer Tools",
    "description": "Generate QR codes via API",
    "base_url": "https://api.qrcode-monkey.com/qr/custom",
    "auth_type": "none",
    "docs_url": "https://www.qrcode-monkey.com/qr-code-api-with-logo/",
    "example_endpoint": "",
    "tags": ["qr-code", "generator", "utility", "images"],
    "status": "unknown"
  },
  {
    "id": "33",
    "name": "URLhaus",
    "category": "Security",
    "description": "Database of malicious URLs used for malware distribution",
    "base_url": "https://urlhaus-api.abuse.ch/v1",
    "auth_type": "none",
    "docs_url": "https://urlhaus-api.abuse.ch/",
    "example_endpoint": "/urls/recent/limit/5/",
    "tags": ["security", "malware", "threat-intel", "urls"],
    "status": "unknown"
  },
  {
    "id": "34",
    "name": "Have I Been Pwned",
    "category": "Security",
    "description": "Check if an email or username has been compromised in data breaches",
    "base_url": "https://haveibeenpwned.com/api/v3",
    "auth_type": "apikey",
    "docs_url": "https://haveibeenpwned.com/API/v3",
    "example_endpoint": "/breachedaccount/test@example.com",
    "tags": ["security", "breaches", "passwords", "privacy"],
    "status": "unknown"
  },
  {
    "id": "35",
    "name": "OpenStreetMap Nominatim",
    "category": "Maps",
    "description": "Free geocoding and reverse geocoding service",
    "base_url": "https://nominatim.openstreetmap.org",
    "auth_type": "none",
    "docs_url": "https://nominatim.org/release-docs/develop/api/Overview/",
    "example_endpoint": "/search?q=London&format=json",
    "tags": ["maps", "geocoding", "location", "osm"],
    "status": "unknown"
  },
  {
    "id": "36",
    "name": "Zippopotam.us",
    "category": "Data",
    "description": "Postal code and geolocation data for multiple countries",
    "base_url": "https://api.zippopotam.us",
    "auth_type": "none",
    "docs_url": "http://www.zippopotam.us/",
    "example_endpoint": "/us/90210",
    "tags": ["postal-code", "zip", "geolocation", "address"],
    "status": "unknown"
  },
  {
    "id": "37",
    "name": "Dad Jokes",
    "category": "Entertainment",
    "description": "Random dad jokes API",
    "base_url": "https://icanhazdadjoke.com",
    "auth_type": "none",
    "docs_url": "https://icanhazdadjoke.com/",
    "example_endpoint": "/",
    "tags": ["jokes", "fun", "random", "humor"],
    "status": "unknown"
  },
  {
    "id": "38",
    "name": "JokeAPI",
    "category": "Entertainment",
    "description": "Programming and general jokes with filtering options",
    "base_url": "https://v2.jokeapi.dev/joke",
    "auth_type": "none",
    "docs_url": "https://sv443.net/jokeapi/v2/",
    "example_endpoint": "/Any?safe-mode",
    "tags": ["jokes", "programming", "fun", "random"],
    "status": "unknown"
  },
  {
    "id": "39",
    "name": "Giphy",
    "category": "Entertainment",
    "description": "GIFs and animated stickers API",
    "base_url": "https://api.giphy.com/v1/gifs",
    "auth_type": "apikey",
    "docs_url": "https://developers.giphy.com/docs/api",
    "example_endpoint": "/trending?api_key=YOUR_API_KEY&limit=25",
    "tags": ["gifs", "stickers", "animation", "fun"],
    "status": "unknown"
  },
  {
    "id": "40",
    "name": "Pixabay",
    "category": "Images",
    "description": "Free images and videos API",
    "base_url": "https://pixabay.com/api",
    "auth_type": "apikey",
    "docs_url": "https://pixabay.com/api/docs/",
    "example_endpoint": "?key=YOUR_API_KEY&q=yellow+flowers",
    "tags": ["images", "photos", "videos", "stock"],
    "status": "unknown"
  },
  {
    "id": "41",
    "name": "Numbers API",
    "category": "Entertainment",
    "description": "Interesting facts about numbers and dates",
    "base_url": "http://numbersapi.com",
    "auth_type": "none",
    "docs_url": "http://numbersapi.com/",
    "example_endpoint": "/random/trivia",
    "tags": ["numbers", "facts", "trivia", "fun"],
    "status": "unknown"
  },
  {
    "id": "42",
    "name": "UUID Generator",
    "category": "Developer Tools",
    "description": "Generate UUIDs and GUIDs",
    "base_url": "https://www.uuidtools.com/api/generate",
    "auth_type": "none",
    "docs_url": "https://www.uuidtools.com/api",
    "example_endpoint": "/v1/count/5",
    "tags": ["uuid", "guid", "generator", "utility"],
    "status": "unknown"
  },
  {
    "id": "43",
    "name": "ZipCodeBase",
    "category": "Data",
    "description": "Postal code data and distance calculations",
    "base_url": "https://app.zipcodebase.com/api/v1",
    "auth_type": "apikey",
    "docs_url": "https://zipcodebase.com/",
    "example_endpoint": "/search?apikey=YOUR_API_KEY&codes=90210",
    "tags": ["postal-code", "zip", "distance", "location"],
    "status": "unknown"
  },
  {
    "id": "44",
    "name": "World Bank",
    "category": "Finance",
    "description": "Global development data from the World Bank",
    "base_url": "https://api.worldbank.org/v2",
    "auth_type": "none",
    "docs_url": "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation",
    "example_endpoint": "/country/all/indicator/SP.POP.TOTL?format=json",
    "tags": ["economics", "development", "countries", "data"],
    "status": "unknown"
  },
  {
    "id": "45",
    "name": "Open Trivia Database",
    "category": "Entertainment",
    "description": "Free trivia questions in various categories",
    "base_url": "https://opentdb.com/api.php",
    "auth_type": "none",
    "docs_url": "https://opentdb.com/api_config.php",
    "example_endpoint": "?amount=10&category=18",
    "tags": ["trivia", "quiz", "questions", "games"],
    "status": "unknown"
  },
  {
    "id": "46",
    "name": "Shibe.online",
    "category": "Entertainment",
    "description": "Random Shiba Inu dog pictures",
    "base_url": "http://shibe.online/api",
    "auth_type": "none",
    "docs_url": "http://shibe.online/",
    "example_endpoint": "/shibes?count=5&urls=true&httpsUrls=true",
    "tags": ["dogs", "shiba", "images", "fun"],
    "status": "unknown"
  },
  {
    "id": "47",
    "name": "PlaceKitten",
    "category": "Images",
    "description": "Kitten placeholder images for your designs",
    "base_url": "https://placekitten.com",
    "auth_type": "none",
    "docs_url": "https://placekitten.com/",
    "example_endpoint": "/200/300",
    "tags": ["images", "placeholder", "cats", "design"],
    "status": "unknown"
  },
  {
    "id": "48",
    "name": "PlaceBear",
    "category": "Images",
    "description": "Bear placeholder images for your designs",
    "base_url": "https://placebear.com",
    "auth_type": "none",
    "docs_url": "https://placebear.com/",
    "example_endpoint": "/200/300",
    "tags": ["images", "placeholder", "bears", "design"],
    "status": "unknown"
  },
  {
    "id": "49",
    "name": "Lorem Picsum",
    "category": "Images",
    "description": "Random placeholder images from Unsplash",
    "base_url": "https://picsum.photos",
    "auth_type": "none",
    "docs_url": "https://picsum.photos/",
    "example_endpoint": "/200/300",
    "tags": ["images", "placeholder", "random", "design"],
    "status": "unknown"
  },
  {
    "id": "50",
    "name": "Meta Weather",
    "category": "Weather",
    "description": "Global weather data from various sources",
    "base_url": "https://www.metaweather.com/api",
    "auth_type": "none",
    "docs_url": "https://www.metaweather.com/api/",
    "example_endpoint": "/location/44418/",
    "tags": ["weather", "forecast", "global", "data"],
    "status": "unknown"
  },
  {
    "id": "51",
    "name": "CoinDesk",
    "category": "Finance",
    "description": "Bitcoin Price Index (BPI) in real-time",
    "base_url": "https://api.coindesk.com/v1/bpi",
    "auth_type": "none",
    "docs_url": "https://www.coindesk.com/coindesk-api",
    "example_endpoint": "/currentprice.json",
    "tags": ["bitcoin", "crypto", "price", "finance"],
    "status": "unknown"
  },
  {
    "id": "52",
    "name": "Breaking Bad Quotes",
    "category": "Entertainment",
    "description": "Quotes from Breaking Bad and Better Call Saul",
    "base_url": "https://api.breakingbadquotes.xyz/v1",
    "auth_type": "none",
    "docs_url": "https://github.com/shevabam/breaking-bad-quotes",
    "example_endpoint": "/quotes",
    "tags": ["quotes", "tv", "breaking-bad", "fun"],
    "status": "unknown"
  },
  {
    "id": "53",
    "name": "Studio Ghibli",
    "category": "Entertainment",
    "description": "Studio Ghibli films, people, locations, and species data",
    "base_url": "https://ghibliapi.vercel.app",
    "auth_type": "none",
    "docs_url": "https://ghibliapi.vercel.app/",
    "example_endpoint": "/films",
    "tags": ["anime", "ghibli", "movies", "japan"],
    "status": "unknown"
  },
  {
    "id": "54",
    "name": "Open Food Facts",
    "category": "Food & Drink",
    "description": "Food product data including ingredients and nutrition",
    "base_url": "https://world.openfoodfacts.org/api/v0",
    "auth_type": "none",
    "docs_url": "https://world.openfoodfacts.org/data",
    "example_endpoint": "/product/737628064502.json",
    "tags": ["food", "nutrition", "products", "health"],
    "status": "unknown"
  },
  {
    "id": "55",
    "name": "FreeToGame",
    "category": "Entertainment",
    "description": "Database of free-to-play games",
    "base_url": "https://www.freetogame.com/api",
    "auth_type": "none",
    "docs_url": "https://www.freetogame.com/api-doc",
    "example_endpoint": "/games",
    "tags": ["games", "free", "gaming", "pc"],
    "status": "unknown"
  }
]
'''

with open(f"{base_path}/packages/api-directory/data/apis.json", "w") as f:
    f.write(apis_data)

print("✅ APIs data file created with 55 real APIs")
