
# CLI init command
init_command = '''import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';

/**
 * Project templates configuration
 */
const templates = {
  node: {
    name: 'Node.js',
    files: {
      'package.json': JSON.stringify({
        name: '{{name}}',
        version: '1.0.0',
        description: '',
        main: 'index.js',
        scripts: {
          start: 'node index.js',
          dev: 'nodemon index.js',
          test: 'jest'
        },
        keywords: [],
        author: '',
        license: 'MIT',
        dependencies: {},
        devDependencies: {
          nodemon: '^3.0.2',
          jest: '^29.7.0'
        }
      }, null, 2),
      'index.js': `console.log('Hello from {{name}}!');`,
      '.gitignore': `node_modules/
.env
.DS_Store
*.log`,
      'README.md': `# {{name}}\n\nNode.js project generated by DevSuite CLI`
    }
  },
  react: {
    name: 'React (Vite)',
    files: {
      'package.json': JSON.stringify({
        name: '{{name}}',
        private: true,
        version: '1.0.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview'
        },
        dependencies: {
          react: '^18.2.0',
          'react-dom': '^18.2.0'
        },
        devDependencies: {
          '@types/react': '^18.2.43',
          '@types/react-dom': '^18.2.17',
          '@vitejs/plugin-react': '^4.2.1',
          vite: '^5.0.8'
        }
      }, null, 2),
      'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{name}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`,
      'src/main.jsx': `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,
      'src/App.jsx': `import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>{{name}}</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
    </>
  )
}

export default App`,
      'src/index.css': `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color-scheme: light dark;
  font-synthesis: none;
  text-rendering: optimizeLegibility;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}`,
      'src/App.css': `#root {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.card {
  padding: 2em;
}`,
      '.gitignore': `node_modules/
.DS_Store
dist
dist-ssr
*.local`,
      'README.md': `# {{name}}\n\nReact + Vite project generated by DevSuite CLI`
    }
  },
  next: {
    name: 'Next.js 14',
    files: {
      'package.json': JSON.stringify({
        name: '{{name}}',
        version: '1.0.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint'
        },
        dependencies: {
          next: '14.0.4',
          react: '^18',
          'react-dom': '^18'
        },
        devDependencies: {
          '@types/node': '^20',
          '@types/react': '^18',
          '@types/react-dom': '^18',
          typescript: '^5',
          eslint: '^8',
          'eslint-config-next': '14.0.4'
        }
      }, null, 2),
      'next.config.js': `/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig`,
      'tsconfig.json': JSON.stringify({
        compilerOptions: {
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./*'] }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
      }, null, 2),
      'src/app/layout.tsx': `export const metadata = {
  title: '{{name}}',
  description: 'Generated by DevSuite CLI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
      'src/app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold">Welcome to {{name}}</h1>
      <p className="mt-4 text-lg">Next.js 14 project generated by DevSuite CLI</p>
    </main>
  )
}`,
      'src/app/globals.css': `* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
  overflow-x: hidden;
}`,
      '.gitignore': `node_modules/
.DS_Store
.next/
out/
*.log`,
      'README.md': `# {{name}}\n\nNext.js 14 project generated by DevSuite CLI`
    }
  },
  python: {
    name: 'Python',
    files: {
      'requirements.txt': `# {{name}} requirements
pytest>=7.4.0
black>=23.0.0
flake8>=6.0.0`,
      'main.py': `#!/usr/bin/env python3
\"\"\"
{{name}} - Main entry point
\"\"\"

def main():
    print(f"Hello from {{name}}!")

if __name__ == "__main__":
    main()`,
      'setup.py': `from setuptools import setup, find_packages

setup(
    name='{{name}}',
    version='1.0.0',
    packages=find_packages(),
    install_requires=[],
    python_requires='>=3.8',
)`,
      '.gitignore': `__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
.env
.venv
env/
venv/
.idea/
.vscode/`,
      'README.md': `# {{name}}\n\nPython project generated by DevSuite CLI`,
      'tests/test_main.py': `import pytest
from main import main

def test_main():
    assert main() is None  # Update with actual tests`
    }
  },
  fastapi: {
    name: 'FastAPI',
    files: {
      'requirements.txt': `fastapi>=0.104.0
uvicorn[standard]>=0.24.0
pydantic>=2.5.0
pytest>=7.4.0
httpx>=0.25.0`,
      'main.py': `from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="{{name}}")

class Item(BaseModel):
    name: str
    description: str | None = None
    price: float
    tax: float | None = None

@app.get("/")
async def root():
    return {"message": "Hello from {{name}}!"}

@app.get("/items/{item_id}")
async def read_item(item_id: int, q: str | None = None):
    return {"item_id": item_id, "q": q}

@app.post("/items/")
async def create_item(item: Item):
    return item`,
      'Dockerfile': `FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]`,
      'docker-compose.yml': `version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development`,
      '.gitignore': `__pycache__/
*.py[cod]
*$py.class
.env
.venv/
.idea/
.vscode/`,
      'README.md': `# {{name}}\n\nFastAPI project generated by DevSuite CLI\n\n## Run\n\n\`\`\`bash\nuvicorn main:app --reload\n\`\`\``
    }
  }
};

/**
 * Initialize a new project with the specified template
 * @param {string} projectName - Name of the project
 * @param {Object} options - Command options
 */
export async function initCommand(projectName, options) {
  const spinner = ora('Initializing project...').start();
  
  try {
    let template = options.template;
    
    // If template not specified, prompt user
    if (!template || !templates[template]) {
      spinner.stop();
      const answers = await inquirer.prompt([
        {
          type: 'list',
          name: 'template',
          message: 'Choose a project template:',
          choices: Object.entries(templates).map(([key, t]) => ({
            name: t.name,
            value: key
          }))
        }
      ]);
      template = answers.template;
      spinner.start();
    }
    
    const targetDir = path.resolve(process.cwd(), projectName);
    
    // Check if directory exists
    if (await fs.pathExists(targetDir)) {
      spinner.fail(chalk.red(`Directory ${projectName} already exists!`));
      process.exit(1);
    }
    
    // Create directory
    await fs.ensureDir(targetDir);
    
    // Get template files
    const templateData = templates[template];
    
    // Create files
    for (const [filePath, content] of Object.entries(templateData.files)) {
      const fullPath = path.join(targetDir, filePath);
      await fs.ensureDir(path.dirname(fullPath));
      
      // Replace template variables
      const processedContent = content.replace(/\{\{name\}\}/g, projectName);
      await fs.writeFile(fullPath, processedContent);
    }
    
    spinner.succeed(chalk.green(`Created ${templateData.name} project: ${projectName}`));
    
    console.log(chalk.cyan('\\nNext steps:'));
    console.log(chalk.white(`  cd ${projectName}`));
    
    if (template === 'node' || template === 'react' || template === 'next') {
      console.log(chalk.white('  npm install'));
      console.log(chalk.white('  npm run dev'));
    } else if (template === 'python' || template === 'fastapi') {
      console.log(chalk.white('  pip install -r requirements.txt'));
      if (template === 'fastapi') {
        console.log(chalk.white('  uvicorn main:app --reload'));
      } else {
        console.log(chalk.white('  python main.py'));
      }
    }
    
  } catch (error) {
    spinner.fail(chalk.red(`Error: ${error.message}`));
    process.exit(1);
  }
}
'''

with open(f"{base_path}/packages/cli/src/commands/init.js", "w") as f:
    f.write(init_command)

print("✅ CLI init command created")
